---
- name: Converge
  hosts: all
  gather_facts: true
  become: false

  vars:
    backup_server: "{{ inventory_hostname }}"
    restic_server_user: lololol
    restic_server_group: backup

  tasks:
    - name: "Include ansible-role-restic_server"
      ansible.builtin.include_role:
        name: "fifty2technology.restic_server"
