---
- name: Converge
  hosts: all
  gather_facts: true
  become: false

  vars:
    restic_server_user: lololol
    restic_server_group: backup
    restic_server_version: "0.10.0"

  tasks:
    - name: "Include ansible-role-restic_server"
      ansible.builtin.include_role:
        name: "fifty2technology.restic_server"
