---

- name: Template rest-server systemd service file
  ansible.builtin.template:
    src: templates/restic-rest-server.service.j2
    dest: /etc/systemd/system/restic-rest-server.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Restart rest-server
  become: true

- name: Create .htpasswd file
  ansible.builtin.file:
    path: "{{ restic_server_backup_path }}/.htpasswd"
    state: touch
    modification_time: preserve
    access_time: preserve
    owner: "{{ restic_server_user }}"
    group: "{{ restic_server_group }}"
    mode: '0600'
  become: true
