---

- name: Template rest-server systemd service file
  ansible.builtin.template:
    src: templates/restic-rest-server.service.j2
    dest: /etc/systemd/system/restic-rest-server.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Restart rest-server
  become: true
