---

###
# See 'vars/main.yml' for package selection.
###
- name: Install packages for rest-server
  ansible.builtin.package:
    name: "{{ restic_server_packages }}"
    state: present

###
# Creates a disabled user account (disabled: can't login via shell)
###
- name: Create backup user
  ansible.builtin.user:
    name: rest-server
    password: '*'
    shell: /usr/sbin/nologin
    state: present

- name: Create directory for backups
  ansible.builtin.file:
    path: "{{ restic_server_backup_path }}"
    owner: "{{ restic_server_user }}"
    group: "{{ restic_server_group }}"
    mode: '0700'
    state: directory

###
# Install from local
###
- name: Install rest-server from locally provided directory
  ansible.builtin.copy:
    src: "{{ restic_server_binary_install_dir }}/rest-server"
    dest: /usr/local/bin/rest-server
    owner: root
    group: rest-server
    mode: '0750'
  become: true
  notify: Restart rest-server
  when:
    - restic_server_binary_install_dir | length > 0

###
# Install directly from GitHub
###
- name: Download, checksum and unpack 'rest-server' from GitHub
  block:
    - name: Get checksum list
      ansible.builtin.set_fact:
        _restic_server_rest_checksums: "{{ lookup('url', 'https://github.com/restic/rest-server/releases/download/v' + _version + '/SHA256SUMS', wantlist=True) | list }}"
      run_once: true

    - name: Filter for checksum of amd64 architecture
      ansible.builtin.set_fact:
        _restic_server_rest_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _restic_server_rest_checksums }}"
      when:
        - "'linux_amd64.tar.gz'in item"

    - name: Download rest-server binary from GitHub - version {{ _version }}
      ansible.builtin.get_url:
        url: "https://github.com/restic/rest-server/releases/download/v{{ _version }}/rest-server_{{ _version }}_linux_amd64.tar.gz"
        dest: "/tmp/rest-server_{{ _version }}_linux_amd64.tar.gz"
        checksum: "sha256:{{ _restic_server_rest_checksum }}"
        mode: '0640'
      register: _download_archive
      changed_when: false
      until: _download_archive is succeeded
      retries: 3
      delay: 5
      notify: Clean up temporary downloads

    - name: Unpack rest-server archive
      ansible.builtin.unarchive:
        src: "/tmp/rest-server_{{ _version }}_linux_amd64.tar.gz"
        dest: /tmp
        mode: '0755'
      notify: Clean up temporary downloads
  delegate_to: localhost
  vars:
    _version: "{{ _restic_server_version_available | default(restic_server_version) }}"
  when:
    - restic_server_binary_install_dir | length == 0

- name: Move rest-server binary into place
  ansible.builtin.copy:
    src: "/tmp/rest-server_{{ _version }}_linux_amd64/rest-server"
    dest: /usr/local/bin/rest-server
    owner: root
    group: rest-server
    mode: '0750'
  become: true
  notify: Restart rest-server
  vars:
    _version: "{{ _restic_server_version_available | default(restic_server_version) }}"
  when:
    - restic_server_binary_install_dir | length == 0
