---

###
# Install from local
###
- name: Install rest-server from locally provided directory
  ansible.builtin.copy:
    src: "{{ restic_server_from_local_dir }}/rest-server"
    dest: "{{ restic_server_install_dir }}/rest-server"
    owner: root
    group: "{{ restic_server_group }}"
    mode: '0750'
  become: true
  notify: Restart rest-server
  when:
    - restic_server_from_local_dir | length > 0

###
# Install directly from GitHub
###
- name: Download, checksum and unpack 'rest-server' from GitHub
  block:
    - name: Get checksum list
      ansible.builtin.set_fact:
        _restic_server_rest_checksums: "{{ lookup('url', 'https://github.com/restic/rest-server/releases/download/v' + _version + '/SHA256SUMS', wantlist=True) | list }}"
      run_once: true

    - name: Filter for checksum of correct architecture
      ansible.builtin.set_fact:
        _restic_server_rest_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _restic_server_rest_checksums }}"
      when:
        - _restic_server_arch in item
        - "'linux' in item"

    - name: Download rest-server binary from GitHub - version {{ _version }}
      ansible.builtin.get_url:
        url: "https://github.com/restic/rest-server/releases/download/v{{ _version }}/rest-server_{{ _version }}_linux_{{ _restic_server_arch }}.tar.gz"
        dest: "/tmp/rest-server_{{ _version }}_linux_{{ _restic_server_arch }}.tar.gz"
        checksum: "sha256:{{ _restic_server_rest_checksum }}"
        mode: '0640'
      register: _download_archive
      changed_when: false
      until: _download_archive is succeeded
      retries: 3
      delay: 5
      notify: Clean up temporary downloads

    - name: Unpack rest-server archive
      ansible.builtin.unarchive:
        src: "/tmp/rest-server_{{ _version }}_linux_{{ _restic_server_arch }}.tar.gz"
        dest: /tmp
        mode: '0755'
      notify: Clean up temporary downloads
  delegate_to: localhost
  run_once: true
  vars:
    _version: "{{ _restic_server_version_available | default(restic_server_version) }}"
  when:
    - restic_server_from_local_dir | length == 0

- name: Move rest-server binary into place
  ansible.builtin.copy:
    src: "/tmp/rest-server_{{ _version }}_linux_{{ _restic_server_arch }}/rest-server"
    dest: "{{ restic_server_install_dir }}/rest-server"
    owner: root
    group: "{{ restic_server_group }}"
    mode: '0750'
  become: true
  notify: Restart rest-server
  vars:
    _version: "{{ _restic_server_version_available | default(restic_server_version) }}"
  when:
    - restic_server_from_local_dir | length == 0
