---

- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

###
# Creates a disabled user account (disabled: can't login via shell)
###
- name: Create backup user
  ansible.builtin.user:
    name: rest-server
    password: '*'
    shell: /usr/sbin/nologin
    state: present

- name: Create directory for backups
  ansible.builtin.file:
    path: "{{ restic_server_backup_path }}"
    owner: "{{ restic_server_user }}"
    group: "{{ restic_server_group }}"
    mode: '0700'
    state: directory

- name: Check for existing rest-server installation
  ansible.builtin.stat:
    path: /usr/local/bin/rest-server
  register: _restic_server_rest_binary

###
# This assumes at least rest-server version 0.10.0 (current version as of
# writing this), since older versions don't have a '--version' knob.
###
- name: Get version of currently installed rest-server version
  ansible.builtin.command:
    cmd: /usr/local/bin/rest-server --version
  register: _raw_restic_server_version_installed
  changed_when: false
  when:
    - _restic_server_rest_binary.stat.exists
