---

- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

- name: Check for existing rest-server installation
  ansible.builtin.stat:
    path: /usr/local/bin/rest-server
  register: _restic_server_rest_binary

###
# This assumes at least rest-server version 0.10.0 (current version as of
# writing this), since older versions don't have a '--version' knob.
###
- name: Get version of currently installed rest-server version
  ansible.builtin.command:
    cmd: /usr/local/bin/rest-server --version
  register: _raw_restic_server_version_installed
  changed_when: false
  when:
    - _restic_server_rest_binary.stat.exists

###
# Only if 'restic_server_version' is set to "latest".
# Inspired by cloudalchemy.prometheus role.
###
- name: Get current version from GitHub
  block:
    - name: Get latest release of rest-server
      ansible.builtin.uri:
        url: "https://api.github.com/repos/restic/rest-server/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
      register: _latest_release
      until: _latest_release.status == 200
      retries: 3
      delay: 5
      changed_when: false
      delegate_to: localhost
      become: false

    - name: Extract latest version number from GitHub API response
      ansible.builtin.set_fact:
        _restic_server_version_available: "{{ _latest_release.json.tag_name[1:] }}"
  when:
    - restic_server_version == 'latest'
