---

- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

###
# Only if 'restic_server_version' is set to "latest".
# Inspired by cloudalchemy.prometheus role.
###
- name: Get current version from GitHub
  block:
    - name: Get latest release of rest-server
      ansible.builtin.uri:
        url: "https://api.github.com/repos/restic/rest-server/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
      register: _latest_release
      until: _latest_release.status == 200
      retries: 3
      delay: 5
      changed_when: false
      delegate_to: localhost
      run_once: true

    - name: Extract latest version number from GitHub API response
      ansible.builtin.set_fact:
        _restic_server_version_available: "{{ _latest_release.json.tag_name[1:] }}"
  when:
    - restic_server_binary_install_dir | length == 0
    - restic_server_version == 'latest'

- name: Update package cache (Debian)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  become: true
  when:
    - "ansible_os_family == 'Debian'"
