---

- name: Clean up temporary downloads
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  delegate_to: localhost
  run_once: true
  loop:
    - "/tmp/rest-server_{{ _version }}_linux_amd64.tar.gz"
    - "/tmp/rest-server_{{ _version }}_linux_amd64/"
  vars:
    _version: "{{ _restic_server_version_available | default(restic_server_version) }}"

- name: reload systemd
  ansible.builtin.systemd:
    daemon-reload: true

- name: reload rest-server
  ansible.builtin.systemd:
    name: restic-rest-server
    enabled: true
    state: reloaded

- name: restart rest-server
  ansible.builtin.systemd:
    name: restic-rest-server
    enabled: true
    state: restarted
