---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    backup_server: "{{ inventory_hostname }}"
    restic_server_version: "0.10.0"

  tasks:
    - name: "Include fifty2technology.restic_server"
      ansible.builtin.include_role:
        name: "fifty2technology.restic_server"
