---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Get rest-server version output
    ansible.builtin.command:
      cmd: /usr/local/bin/rest-server --version
    register: _version_output

  ###
  # Take care, '--version' output changed with rest-server version 0.11.0, it
  # would be "split(' ')[3]" then.
  ###
  - name: Assert correct output
    ansible.builtin.assert:
      that:
        - "_version_output.stdout.split(' ')[1] == '0.10.0'"
