---

- name: Verify
  hosts: all
  gather_facts: false

  ### needed because we don't run the whole role here, but need to know where our stuff is installed
  vars:
    restic_server_install_dir: /usr/local/bin

  tasks:
  - name: Get file hash of local binary
    ansible.builtin.stat:
      path: /tmp/rest-server
      checksum_algorithm: sha256
    register: _molecule_local_bin
    delegate_to: localhost

  - name: Get file hash of remote binary
    ansible.builtin.stat:
      path: "{{ restic_server_install_dir }}/rest-server"
      checksum_algorithm: sha256
    register: _molecule_remote_bin

  - name: Assert that file hashes are identical
    ansible.builtin.assert:
      that:
        - _molecule_local_bin.stat.checksum == _molecule_remote_bin.stat.checksum
