---
- name: Converge
  hosts: all

  vars:
    backup_server: "{{ inventory_hostname }}"

  tasks:
    - name: "Include ansible-role-restic_server"
      ansible.builtin.include_role:
        name: "ansible-role-restic_server"
