---
- name: Converge
  hosts: all
  gather_facts: true
  become: false

  tasks:
    - name: "Include ansible-role-restic_server"
      ansible.builtin.include_role:
        name: "fifty2technology.restic_server"
