---

- name: Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: Force update package cache (Debian)
      ansible.builtin.apt:
        update_cache: true
      become: true
      when:
        - "ansible_os_family == 'Debian'"
